const TABLE_WIDTH = 5;
const TABLE_HEIGHT = 5;
const ZERO_POS = { x: 0, y: 0};
const FACE_NORTH = 1;
const FACE_WEST = 2;
const FACE_SOUTH = 3;
const FACE_EAST = 4;
const ROBOT_FACES = [FACE_NORTH, FACE_WEST, FACE_SOUTH, FACE_EAST];

module.exports = {
  TABLE_WIDTH,
  TABLE_HEIGHT,
  ZERO_POS,
  ROBOT_FACES,
  FACE_NORTH,
  FACE_WEST,
  FACE_SOUTH,
  FACE_EAST
};
